name: network_logger
description: Network logger with well designed user interface to inspect network traffic logs. Included with Dio interceptor.
version: 1.0.4
homepage: https://github.com/themisir/flutter-network-logger

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.1"

dependencies:
  dio: ">=4.0.0 <6.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
